### ISSUE TITLE
Syntax error on startup

### ISSUE THREAD

**Issue by apetresc** [yishn/LeelaSabaki#1]
When invoking `leelasabaki`, either from the CLI or through Sabaki, it immediately crashes with:

```
/snapshot/LeelaSabaki/src/index.js:95
lineReader.on('line', async input => {
                      ^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Module._compile (pkg/prelude/bootstrap.js:1250:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (pkg/prelude/bootstrap.js:1298:12)
    at run (bootstrap_node.js:419:7)
```
I don't know anything about the NodeJS ecosystem, but this smells like some sort of language version mismatch to me. I'm running:

```
$ node --version
v6.10.3
$ npm --version
3.10.10
```

**Comment by yishn** [comment]
Yes, you need a node version that supports async functions; I think version 8 is okay. This should probably be documented in the 'Building' section.

**Comment by yishn** [comment]
Ah, I see what's going on, the build script doesn't specify the node version to be used, so it defaults to the node version you have installed on your system. This should probably be fixed.

**Comment by apetresc** [comment]
Indeed, this solved it :) Thanks!
